
#ifndef LED_CUBE_CONTROLLER_CONSTANTS_H
#define LED_CUBE_CONTROLLER_CONSTANTS_H

#define BAUDRATE 19200
#define WIFI_SSID "hrd-hotspot"
#define WIFI_PASSWORD "404D17815D896AE9DFC95087C0"
#define API_PASSWORD ""


#define WEBSERVER_PORT 80
#define FRAME_LENGTH 64

#endif